name: BLADE
channels:
  - bioconda
  - conda-forge
dependencies:
  - jupyter
  - numpy
  - numba
  - scikit-learn
  - joblib
  - multiprocess
  - time
  - scipy
  - qgrid
  - seaborn
  - pip
  - pip:
      - BLADE-Deconvolution
